# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\Desktop\FLJ\ZhouChuanHong\tongji.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from real_time_db1 import ImageProcessor
from real_time_db1 import ShiftSetting

import sqlite3
processor=ImageProcessor()

shift_process=ShiftSetting()

import sys

from PyQt5 import QtCore, QtGui, QtWidgets

pingpaitotal = ["大丰收（软）01M","红金龙（硬红）01M","红金龙（软红之彩）01M","红金龙（软红之彩）02M","红金龙（软红之彩）03M"]
barcode = ['06103','02202','02180','02107','02162']

conn = sqlite3.connect('real_time_db.db')
cur = conn.cursor()


cur.execute("SELECT year FROM image")
year_in_sqlite = cur.fetchall() 

cur.execute("SELECT month FROM image")
month_in_sqlite = cur.fetchall() 

cur.execute("SELECT day FROM image")
day_in_sqlite = cur.fetchall() 

cur.execute("SELECT hour FROM image")
hour_in_sqlite = cur.fetchall() 

cur.execute("SELECT minute FROM image")
minute_in_sqlite = cur.fetchall() 

cur.execute("SELECT image_path FROM image")
image_path_in_sqlite = cur.fetchall() 

cur.execute("SELECT barcode FROM image")
barcode_in_sqlite = cur.fetchall() 

cur.execute("SELECT product_name FROM image")
product_name_in_sqlite = cur.fetchall() 


class Tongji1(QtWidgets.QMainWindow):
    
    def __init__(self):
           super(Tongji1,self).__init__()
           self.setupUi(self)
           self.retranslateUi(self)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 656)
        MainWindow.setMinimumSize(QtCore.QSize(1036, 656))
        MainWindow.setMaximumSize(QtCore.QSize(1036, 656))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("#frame{\n"
"border-image: url(:/images/images/background.png);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_info = QtWidgets.QWidget(self.frame)
        self.widget_info.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_info.setMaximumSize(QtCore.QSize(10101010, 16777215))
        self.widget_info.setStyleSheet("#widget_info{\n"
"    background-color: rgb(255, 255, 255);\n"
"     border-radius:8px;\n"
"\n"
"}")
        self.widget_info.setObjectName("widget_info")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget_info)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 20, 61, 31))
        self.textBrowser_2.setStyleSheet("border:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame_7 = QtWidgets.QFrame(self.widget_info)
        self.frame_7.setGeometry(QtCore.QRect(50, 50, 901, 521))
        self.frame_7.setStyleSheet("#frame_7{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"    background-color: rgb(241, 241, 241);\n"
"\n"
"}\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setGeometry(QtCore.QRect(230, 100, 471, 42))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.yearcomboBox22 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yearcomboBox22.setFont(font)
        self.yearcomboBox22.setObjectName("yearcomboBox22")
        self.ncb7 = 2000#循环下拉菜单项目
        while self.ncb7 <=2024 :
            
            self.yearcomboBox22.addItem(str(self.ncb7))
            self.ncb7 += 1
        self.horizontalLayout_3.addWidget(self.yearcomboBox22)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.moncomboBox22 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moncomboBox22.setFont(font)
        self.moncomboBox22.setObjectName("moncomboBox22")

        self.ncb7 = 0#循环下拉菜单项目
        while self.ncb7 <=11 :
            self.ncb7 += 1
            self.moncomboBox22.addItem(str(self.ncb7))


        self.horizontalLayout_3.addWidget(self.moncomboBox22)
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.datecomboBox22 = QtWidgets.QComboBox(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.datecomboBox22.setFont(font)
        self.datecomboBox22.setObjectName("datecomboBox22")
        self.ncb7 = 0
        while self.ncb7 <=30 :
            self.ncb7 += 1
            self.datecomboBox22.addItem(str(self.ncb7))

        self.horizontalLayout_3.addWidget(self.datecomboBox22)
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setGeometry(QtCore.QRect(230, 180, 471, 42))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_10.setFont(font)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.yearcomboBox33 = QtWidgets.QComboBox(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yearcomboBox33.setFont(font)
        self.yearcomboBox33.setObjectName("yearcomboBox33")
        self.ncb7 = 2000#循环下拉菜单项目
        while self.ncb7 <=2024 :
            
            self.yearcomboBox33.addItem(str(self.ncb7))
            self.ncb7 += 1


        self.horizontalLayout_7.addWidget(self.yearcomboBox33)
        self.label_17 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.moncomboBox33 = QtWidgets.QComboBox(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moncomboBox33.setFont(font)
        self.moncomboBox33.setObjectName("moncomboBox33")
        self.ncb7 = 0#循环下拉菜单项目
        while self.ncb7 <=11 :
            self.ncb7 += 1
            self.moncomboBox33.addItem(str(self.ncb7))


  
        self.horizontalLayout_7.addWidget(self.moncomboBox33)
        self.label_18 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.datecomBox33 = QtWidgets.QComboBox(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.datecomBox33.setFont(font)
        self.datecomBox33.setObjectName("datecomBox33")
        self.ncb7 = 0
        while self.ncb7 <=30 :
            self.ncb7 += 1
            self.datecomBox33.addItem(str(self.ncb7))
        self.horizontalLayout_7.addWidget(self.datecomBox33)
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.frame_6 = QtWidgets.QFrame(self.frame_7)
        self.frame_6.setGeometry(QtCore.QRect(320, 250, 261, 42))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_6.setFont(font)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.pingpaicomboBox = QtWidgets.QComboBox(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pingpaicomboBox.setFont(font)
        self.pingpaicomboBox.setObjectName("pingpaicomboBox")###品牌   ！！！！！！！！
        
        
        
        self.ncb8 = 0#循环下拉菜单项目
        while self.ncb8 < 5 :
            
            self.pingpaicomboBox.addItem(pingpaitotal[int(self.ncb8)])

            self.ncb8 += 1
        

        self.horizontalLayout_5.addWidget(self.pingpaicomboBox)
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setGeometry(QtCore.QRect(330, 390, 231, 65))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_11.setFont(font)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_20 = QtWidgets.QLabel(self.frame_11)
        self.label_20.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_8.addWidget(self.label_20)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_11)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 100,100))
        self.textBrowser.setStyleSheet("\n"
"border:none;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_8.addWidget(self.textBrowser)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_5.setGeometry(QtCore.QRect(400, 320, 105, 32))
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"background-color: rgb(186, 186, 186);\n"
"border:2px solid rgb(150, 150, 150) ;\n"
"}\n"
"\n"
"#pushButton_5:hover{\n"
"background-color: rgb(162, 162, 162);\n"
"color:black;\n"
"}\n"
"\n"
"\n"
"\n"
"#pushButton_5:pressed{\n"
"background-color:  rgb(120, 120, 120);\n"
"color:black;\n"
"padding-top:3px;\n"
"padding-left:3px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_6.setGeometry(QtCore.QRect(780, 470, 105, 32))
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("#pushButton_6{\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"background-color: rgb(186, 186, 186);\n"
"border:2px solid rgb(150, 150, 150) ;\n"
"}\n"
"\n"
"#pushButton_6:hover{\n"
"background-color: rgb(162, 162, 162);\n"
"color:black;\n"
"}\n"
"\n"
"\n"
"\n"
"#pushButton_5:pressed{\n"
"background-color:  rgb(120, 120, 120);\n"
"color:black;\n"
"padding-top:3px;\n"
"padding-left:3px;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.widget_info)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
########################开始写功能
########################开始写功能
########################开始写功能
########################开始写功能
########################开始写功能
########################开始写功能


###定义变量
        self.startyear =self.yearcomboBox22.currentText() 
        self.starmonth =self.moncomboBox22.currentText() 
        self.startday =self.datecomboBox22.currentText() 
        self.finishyear =self.yearcomboBox33.currentText() 
        self.finishmonth =self.moncomboBox33.currentText()   
        self.finishday =self.datecomBox33.currentText()   
        self.pingpai = self.pingpaicomboBox.currentText()







#####当下拉索引发生改变时发射信号触发绑定的事件

        self.yearcomboBox22.currentIndexChanged.connect(self.comboBox_currentlycatch)
        self.moncomboBox22.currentIndexChanged.connect(self.comboBox_currentlycatch)
        self.datecomboBox22.currentIndexChanged.connect(self.comboBox_currentlycatch)
        self.yearcomboBox33.currentIndexChanged.connect(self.comboBox_currentlycatch)
        self.moncomboBox33.currentIndexChanged.connect(self.comboBox_currentlycatch)
        self.datecomBox33.currentIndexChanged.connect(self.comboBox_currentlycatch)
        self.pingpaicomboBox.currentIndexChanged.connect(self.comboBox_currentlycatch)







    def tongji_fuc(self):

        self.counter1 = 0

        self.yearcounter = 0

        self.totalstarttime = int(self.startyear)*12*31+int(self.starmonth)*31+int(self.startday)

        self.totalendtime = int(self.finishyear)*12*31+int(self.finishmonth)*31+int(self.finishday)

        if self.totalstarttime > self.totalendtime :
            self.new_html2 = f"<h2 style='text-align: center;'> 无</h2>"
            self.textBrowser.setHtml(self.new_html2)




        else :
            while self.counter1 < len(year_in_sqlite):
                self.currenttime = int(year_in_sqlite[self.counter1][0])*12*31+int(month_in_sqlite[self.counter1][0])*31+int(day_in_sqlite[self.counter1][0])

                if  self.currenttime>=self.totalstarttime and self.currenttime<= self.totalendtime  and (product_name_in_sqlite[self.counter1][0] == self.pingpai):
                    self.yearcounter += 1 

                self.counter1 +=1



                

            print(self.yearcounter)

            self.new_html2 = f"<h2 style='text-align: center;'> {self.yearcounter}</h2>"
            self.textBrowser.setHtml(self.new_html2)


      

        
        return









    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:13.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">统计</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "从"))

        self.label_8.setText(_translate("MainWindow", "年"))
        self.label_9.setText(_translate("MainWindow", "月"))
        self.label_14.setText(_translate("MainWindow", "日"))
        self.label_13.setText(_translate("MainWindow", "到"))
        self.label_17.setText(_translate("MainWindow", "年"))
        self.label_18.setText(_translate("MainWindow", "月"))
        self.label_19.setText(_translate("MainWindow", "日"))
        self.label_12.setText(_translate("MainWindow", "品牌"))
        self.label_20.setText(_translate("MainWindow", "数量"))
        self.new_html2 = f"<h2 style='text-align: center;'></h2>"
        self.textBrowser.setHtml(self.new_html2)
        self.pushButton_5.setText(_translate("MainWindow", "统计"))
        self.pushButton_6.setText(_translate("MainWindow", "退出"))
        

        #########按钮事件绑定
        self.pushButton_6.clicked.connect(MainWindow.close)

        self.pushButton_5.clicked.connect(self.tongji_fuc)



    def comboBox_currentlycatch(self): #更新 目前的下拉菜单的数值 到current变量中  下拉菜菜单栏的数值发生变化以后自动更新（不用修改了）
        self.startyear =self.yearcomboBox22.currentText() 
        self.starmonth =self.moncomboBox22.currentText() 
        self.startday =self.datecomboBox22.currentText() 
        self.finishyear =self.yearcomboBox33.currentText() 
        self.finishmonth =self.moncomboBox33.currentText()   
        self.finishday =self.datecomBox33.currentText()   
        self.pingpai = self.pingpaicomboBox.currentText()



import recources_rc




if __name__ == "__main__":
    import sys
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tongji1() 
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
    


    